# Generated by Django 6.0.5 on 2026-05-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2000)),
                ('report_type', models.CharField(choices=[('phishing', 'Phishing / Scam'), ('safe', 'Safe / Legitimate')], max_length=20)),
                ('session_id', models.CharField(blank=True, default='', max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='URLReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2000, unique=True)),
                ('phishing_count', models.PositiveIntegerField(default=0)),
                ('safe_count', models.PositiveIntegerField(default=0)),
                ('community_verdict', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('SAFE', 'Safe'), ('MODERATE', 'Moderate Risk'), ('HIGH', 'High Risk')], default='UNKNOWN', max_length=20)),
                ('last_reported', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-phishing_count', '-last_reported'],
            },
        ),
    ]
